services:
  - type: web
    name: bayservices-backend
    env: node
    repo: https://github.com/Kenny-Corleone/bayservices_system
    branch: master
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: supersecret
      - key: DATABASE_URL
        fromDatabase:
          name: bayservices-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bayservices-redis
          property: connectionString

  - type: web
    name: bayservices-frontend
    env: static
    repo: https://github.com/Kenny-Corleone/bayservices_system
    branch: master
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true

  - type: redis
    name: bayservices-redis
    plan: free
    ipAllowList: ["0.0.0.0/0"]

databases:
  - name: bayservices-db
    plan: free
