services:
  - type: web
    name: bayservices-app
    env: docker
    plan: free
    repo: https://github.com/Kenny-Corleone/bayservices_system
    branch: master
    region: frankfurt
    autoDeploy: true
    envVars:
      - key: JWT_SECRET
        value: supersecret
      - key: DATABASE_URL
        fromService:
          name: bayservices-db
          type: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bayservices-redis
          type: redis
          property: connectionString

databases:
  - name: bayservices-db
    plan: free
    region: frankfurt

redis:
  - name: bayservices-redis
    plan: free
    region: frankfurt
